### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by sicaboy** [ZhukV/AppleApnPush#67]

**Comment by ZhukV** [comment]
@sicaboy thank for issue. I add support PHP 8 in #68 Pull request (Branch: `feature/add-support-php8`). Please install in your project and test. If all OK work, I merge PR and add new tag.

You can have problem in use JWT libraries, because I update them from `~1.0` to `~2.0` for development.

Thank.

P.S. For install in your project, you can add to you `composer.json`:

```json
{
    "require": {
        "apple/apn-push": "dev-feature/add-support-php8"
    }
}
```

**Comment by ZhukV** [comment]
@sicaboy , Can you test #68 ?

**Comment by ZhukV** [comment]
@sicaboy , Can you test #68, or can I close this issue?

**Comment by sicaboy** [comment]
Sorry. I'll have a test ASAP

**Comment by ZhukV** [comment]
@sicaboy , thank, please reply after testing.

**Comment by sicaboy** [comment]
Thanks, @ZhukV  I've tested the branch `dev-feature/add-support-php8` with PHP 8.0.2. Closing this ticket.

**Comment by ZhukV** [comment]
@sicaboy , all correct work?

**Comment by sicaboy** [comment]
Confirming all php unit cases passed with PHP 8.0.5

**Comment by ZhukV** [comment]
Thank. You try use certificate and jwt token authenticators?

**Comment by Sainomori** [comment]
@ZhukV First of all, thank you for your job!
I tested both certificate and JWT on PHP 8.0.3 + Symfony 5.2.6
